# Huge, MEE SUSTech
# Email: zhuhu00@foxmail.com

version: '2.3'
services:
  fasterlio-ubuntu20:
    image: zhuhu/fasterlio-ubuntu20:0.1
    build: .
    command: /bin/bash
      #command: lxterminal
      #runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../../faster-lio:/root/catkin_ws/src/faster-lio
      - ${DATASET_DIR}:/root/Dataset
      - ~/docker/env:/root/env # 存储空间映射，映射到放代码的空间
      - ~/docker/vscode:/root/.vscode-server




    entrypoint: /ros_entrypoint.sh
    network_mode: host
    ports:
      - 22002:22 

volumes:
  fasterlio-ubuntu20:
